version: '3.8'

services:
  ppt-comparator:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      # Optional: Mount volumes for persistent storage
      - ./uploads:/app/uploads
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s